[tool.poetry]
name = "ble-led-strip-camera-control"
version = "0.1.0"
description = "BLE LED Strip Control with Camera-based Brightness Detection"
authors = ["0aaryan <aroraryan826@gmail.com>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
opencv-python = "*"
bleak = "^2.1.1"
fastapi = "^0.104.0"
uvicorn = {extras = ["standard"], version = "^0.24.0"}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
